name: cucumber-tags

on:
  push:
  pull_request:
  workflow_dispatch: 

jobs:
  run-by-tag:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tags: ['@component-Division', '@component-Addition', '@component-EndToEnd', '@component-Subtraction', '@component-Multiplication']
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build & test for ${{ matrix.tags }}
        env:
          CI: true
          ORG_SLF4J_SIMPLELOGGER_LOG_ORG_APACHE_HC_CLIENT5_HTTP: warn
          ORG_SLF4J_SIMPLELOGGER_LOG_ORG_APACHE_HC_CLIENT5_HTTP_WIRE: off
        run: mvn -q test -Dcucumber.filter.tags="${{ matrix.tags }}"

        # If you must run a specific runner class, use:
        # run: mvn -q test -Dtest=cucumberTest.Runner -Dcucumber.filter.tags="${{ matrix.tags }}"
