name: cucumber-tags

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run-by-tag:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tags: ['@component-Division', '@component-Addition', '@component-EndToEnd', '@component-Subtraction', '@component-Multiplication']

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build & test for ${{ matrix.tags }}
        env:
          CI: true
          ORG_SLF4J_SIMPLELOGGER_LOG_ORG_APACHE_HC_CLIENT5_HTTP: warn
          ORG_SLF4J_SIMPLELOGGER_LOG_ORG_APACHE_HC_CLIENT5_HTTP_WIRE: off
          # Optional: relax/focus axe failing criteria
          # AXE_SKIP_RULES: document-title,html-has-lang
          # AXE_MIN_IMPACT: serious
        run: mvn -q test -Dcucumber.filter.tags="${{ matrix.tags }}"

      - name: List axe files
        if: always()
        run: ls -al target/axe || true

      - name: Upload axe JSON (per tag)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: axe-json-${{ matrix.tags }}      # unique to avoid 409 conflicts
          path: target/axe/*.json
          if-no-files-found: warn

  aggregate-report:
    needs: run-by-tag
    if: ${{ always() }}     # <-- IMPORTANT: run even if some matrix jobs failed/cancelled
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Download all per-tag JSON artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: axe-json-*
          path: merged-axe
          merge-multiple: true

      - name: Show merged contents
        run: ls -al merged-axe || true

      - name: Generate combined HTML
        run: |
          # Compile tests so AxeHtmlReporter (in test sources) is available
          mvn -q -DskipTests -Dtest=!Dummy test-compile
          # Run the reporter against the merged folder (creates merged-axe/index.html)
          mvn -q org.codehaus.mojo:exec-maven-plugin:3.3.0:java \
            -Dexec.mainClass=com.automationCalculator.accessibility.AxeHtmlReporter \
            -Dexec.classpathScope=test \
            -Dexec.arguments="merged-axe"

      - name: Upload combined HTML
        uses: actions/upload-artifact@v4
        with:
          name: axe-report-all
          path: merged-axe/index.html
          if-no-files-found: warn

      - name: Summary
        run: |
          echo "## Accessibility Summary (Combined)" >> "$GITHUB_STEP_SUMMARY"
          echo "- Combined report artifact: axe-report-all" >> "$GITHUB_STEP_SUMMARY"
          echo "- Files merged: $(ls -1 merged-axe/*.json 2>/dev/null | wc -l)" >> "$GITHUB_STEP_SUMMARY"
