name: cucumber-axe
on: [push, pull_request, workflow_dispatch]

jobs:
  run-by-tag:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tags: ['@component-Division','@component-Addition','@component-EndToEnd','@component-Subtraction','@component-Multiplication']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: '17', cache: maven }
      - run: rm -rf target/axe && mkdir -p target/axe
      - name: Build & test for ${{ matrix.tags }}
        env:
          CI: true
          ORG_SLF4J_SIMPLELOGGER_LOG_ORG_APACHE_HC_CLIENT5_HTTP: warn
          ORG_SLF4J_SIMPLELOGGER_LOG_ORG_APACHE_HC_CLIENT5_HTTP_WIRE: off
          # AXE_SKIP_RULES: ""
          # AXE_MIN_IMPACT: minor
        run: mvn -q test -Dcucumber.filter.tags="${{ matrix.tags }}"
      - name: List axe files
        if: always()
        run: ls -al target/axe || true
      - name: Compute artifact name
        id: aname
        if: always()
        shell: bash
        run: |
          n="${{ matrix.tags }}"; n="${n//@/at-}"; n="${n// /_}"; echo "val=$n" >> "$GITHUB_OUTPUT"
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: axe-json-${{ steps.aname.outputs.val }}
          path: target/axe/*.json
          if-no-files-found: warn

  aggregate-report:
    needs: run-by-tag
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: '17' }
      - uses: actions/download-artifact@v4
        with: { pattern: axe-json-*, path: merged-axe, merge-multiple: true }
      - name: Show merged contents
        run: |
          ls -al merged-axe || true
          if [ "$(ls -1 merged-axe/*.json 2>/dev/null | wc -l)" -eq 0 ]; then
            echo "::error::No JSON artifacts found in merged-axe"; exit 1; fi
      - name: Compile reporter
        run: mvn -q -DskipTests -Dtest=!Dummy test-compile
      - name: Generate fail-only report
        run: |
          mvn -q org.codehaus.mojo:exec-maven-plugin:3.3.0:java \
            -Dexec.mainClass=com.automationCalculator.accessibility.AxeFailuresFromFullReporter \
            -Dexec.classpathScope=test \
            -Dexec.arguments="merged-axe"
      - uses: actions/upload-artifact@v4
        with:
          name: axe-failures
          path: merged-axe/failures.html
          if-no-files-found: error
